#!/bin/csh

# Usage: capon REPFIL COVFIL

rm -f REPFIL COVFIL SHDFIL

ln -s $1.shd		REPFIL  # replica    file
ln -s $2.cov		COVFIL  # covariance file

capon.exe

rm -f REPFIL COVFIL
mv SHDFIL		$2C.shd # Bartlett power file
