#!/bin/csh

@ ctr = 1
foreach modfil ( $argv[*] )
   rm -f MODFIL$ctr
   ln -s $modfil.mod           MODFIL$ctr  # MODe file (input)
   @ ctr = $ctr + 1
end

fieldmo.exe < fieldmo.flp

rm -f MODFIL*
mv SHDFIL		$1.shd	# SHaDe file

