% angles    computes the take-off angle which turns at a specific sound speed
% bbrun     used to do a broadband run
% beamform  simple beamformer
% bpsk      binary phase shift keying
% field     sums the modes to compute the acoustic field
% Gaussian  generates a gaussian pulse
% hfm       generates an hfm sweep
% lfm       generates an lfm sweep
% LoadArrfil    loads eigenray, arrival information
% makeenv   makes and envfil
% menumaster    gui to launch models
% mseq      generates m-sequences
% Nwave     generates an N-wave
% plotbty   plots the bathymetry
% plotmode  plots KRAKEN modes
% plotray   plots BELLHOP rays
% plotshd   plots a shade file
% plotshdpol plots a shade file in polar coordinates
% plotssp   plots the sound speed profile
% plotssp_dat also plots the ssp, but uses output from plotssp.f
% plotssp_prt also plots the ssp, but uses .prt file
% plottld   plots TL vs. depth (taking a vertical   slice out of a shade file)
% plottlr   plots TL vs. range (taking a horizontal slice out of a shade file)
% plottri   plots the triangulation for a field3d run
% plotts    plots a time-series file produced by SPARC
% plotxy    plots rays in the x-y plane generated by FIELD3D
% rand_bottom   generates a realization of a random bottom
% read_shd  reads the data from a shdfile
% read_bty  reads bottom bathymetry
% Ricker    generates a Ricker wavelet
% stack     does Fourier synthesis to produce a time series