MODULE krakmod

   SAVE

   INTEGER,          PARAMETER :: ENVFIL = 5, PRTFIL = 6, MODFIL = 20, EVMFIL = 22, MAXMED = 500, NSETS = 5
   REAL (KIND=8),    PARAMETER :: PI = 3.1415926535898D0
   COMPLEX (KIND=8), PARAMETER :: CI = ( 0.0, 1.0 ) 

   INTEGER NFACT, NLACT, NMEDIA, NV( NSETS ), ISET, M, LRECL, MODECT, MODE, IPROF

   REAL (KIND=8) :: ET( NSETS ), HV( NSETS ), RHOT, RHOB, CMIN, CLOW, CHIGH, &
                    FREQ, OMEGA2, RMAX, BUMDEN, ETA, XI
   REAL (KIND=8), ALLOCATABLE :: EVMAT( :, : ), EXTRAP( :, : ), VG( : )

   COMPLEX (KIND=8) :: CPT, CST, CPB, CSB
   COMPLEX (KIND=8), ALLOCATABLE :: CK( : )

   ! media properties

   INTEGER LOC(   MAXMED ), NG( MAXMED ), N(     MAXMED )
   REAL (KIND=8) ::  DEPTH( MAXMED ), H(  MAXMED ), SIGMA( MAXMED )

   CHARACTER MATER( MAXMED )*8, TOPOPT*8, BOTOPT*8, TITLE*80
   REAL (KIND=8), ALLOCATABLE :: B1( : ), B1C( : ), B2( : ), B3( : ), B4( : ), RHO( : )

END MODULE krakmod
